// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:clinical_curator/data/collections/allergy_intolerance_collection.dart';
import 'package:clinical_curator/data/collections/ambulance_request_collection.dart';
import 'package:clinical_curator/data/collections/appointment_collection.dart';
import 'package:clinical_curator/data/collections/audit_event_collection.dart';
import 'package:clinical_curator/data/collections/care_plan_collection.dart';
import 'package:clinical_curator/data/collections/condition_collection.dart';
import 'package:clinical_curator/data/collections/encounter_collection.dart';
import 'package:clinical_curator/data/collections/fhir_resource_collection.dart';
import 'package:clinical_curator/data/collections/health_tip_collection.dart';
import 'package:clinical_curator/data/collections/healthcare_service_collection.dart';
import 'package:clinical_curator/data/collections/immunization_collection.dart';
import 'package:clinical_curator/data/collections/insurance_claim_collection.dart';
import 'package:clinical_curator/data/collections/lab_booking_collection.dart';
import 'package:clinical_curator/data/collections/location_collection.dart';
import 'package:clinical_curator/data/collections/medication_request_collection.dart';
import 'package:clinical_curator/data/collections/notification_record_collection.dart';
import 'package:clinical_curator/data/collections/organization_collection.dart';
import 'package:clinical_curator/data/collections/payment_collection.dart';
import 'package:clinical_curator/data/collections/pharmacy_order_collection.dart';
import 'package:clinical_curator/data/collections/practitioner_role_collection.dart';
import 'package:clinical_curator/data/collections/procedure_collection.dart';
import 'package:clinical_curator/data/collections/rbac_permission_collection.dart';
import 'package:clinical_curator/data/collections/schedule_slot_collection.dart';
import 'package:clinical_curator/data/collections/service_request_collection.dart';
import 'package:clinical_curator/data/collections/slot_collection.dart';
import 'package:clinical_curator/data/collections/user_account_collection.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AllergyIntoleranceLocalAdapter());
    registerAdapter(AmbulanceRequestLocalAdapter());
    registerAdapter(AppointmentLocalAdapter());
    registerAdapter(AuditEventLocalAdapter());
    registerAdapter(CarePlanLocalAdapter());
    registerAdapter(ConditionLocalAdapter());
    registerAdapter(EncounterLocalAdapter());
    registerAdapter(FhirResourceAdapter());
    registerAdapter(HealthTipLocalAdapter());
    registerAdapter(HealthcareServiceLocalAdapter());
    registerAdapter(ImmunizationLocalAdapter());
    registerAdapter(InsuranceClaimLocalAdapter());
    registerAdapter(LabBookingLocalAdapter());
    registerAdapter(LocationLocalAdapter());
    registerAdapter(MedicationRequestLocalAdapter());
    registerAdapter(NotificationRecordLocalAdapter());
    registerAdapter(OrganizationLocalAdapter());
    registerAdapter(PaymentLocalAdapter());
    registerAdapter(PharmacyOrderLocalAdapter());
    registerAdapter(PractitionerRoleLocalAdapter());
    registerAdapter(ProcedureLocalAdapter());
    registerAdapter(RbacPermissionLocalAdapter());
    registerAdapter(ScheduleSlotLocalAdapter());
    registerAdapter(ServiceRequestLocalAdapter());
    registerAdapter(SlotLocalAdapter());
    registerAdapter(UserAccountAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AllergyIntoleranceLocalAdapter());
    registerAdapter(AmbulanceRequestLocalAdapter());
    registerAdapter(AppointmentLocalAdapter());
    registerAdapter(AuditEventLocalAdapter());
    registerAdapter(CarePlanLocalAdapter());
    registerAdapter(ConditionLocalAdapter());
    registerAdapter(EncounterLocalAdapter());
    registerAdapter(FhirResourceAdapter());
    registerAdapter(HealthTipLocalAdapter());
    registerAdapter(HealthcareServiceLocalAdapter());
    registerAdapter(ImmunizationLocalAdapter());
    registerAdapter(InsuranceClaimLocalAdapter());
    registerAdapter(LabBookingLocalAdapter());
    registerAdapter(LocationLocalAdapter());
    registerAdapter(MedicationRequestLocalAdapter());
    registerAdapter(NotificationRecordLocalAdapter());
    registerAdapter(OrganizationLocalAdapter());
    registerAdapter(PaymentLocalAdapter());
    registerAdapter(PharmacyOrderLocalAdapter());
    registerAdapter(PractitionerRoleLocalAdapter());
    registerAdapter(ProcedureLocalAdapter());
    registerAdapter(RbacPermissionLocalAdapter());
    registerAdapter(ScheduleSlotLocalAdapter());
    registerAdapter(ServiceRequestLocalAdapter());
    registerAdapter(SlotLocalAdapter());
    registerAdapter(UserAccountAdapter());
  }
}
