name: cc_repositories
description: Abstract repository interfaces + Serverpod-backed implementations. Shared between admin and clinical apps.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  serverpod_flutter: 3.4.5
  clinical_curator_client:
    path: ../../clinical_curator_client

dev_dependencies:
  flutter_lints: ^6.0.0
